# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import resume_pb2 as resume__pb2


class ResumeServiceStub(object):
  """service to request resumes and send them from server
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetResumes = channel.unary_unary(
        '/pb.ResumeService/GetResumes',
        request_serializer=resume__pb2.ResumeRequest.SerializeToString,
        response_deserializer=resume__pb2.ResumeResponse.FromString,
        )
    self.SendResumes = channel.unary_unary(
        '/pb.ResumeService/SendResumes',
        request_serializer=resume__pb2.ResumeResponse.SerializeToString,
        response_deserializer=resume__pb2.ResumeRequest.FromString,
        )


class ResumeServiceServicer(object):
  """service to request resumes and send them from server
  """

  def GetResumes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendResumes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ResumeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetResumes': grpc.unary_unary_rpc_method_handler(
          servicer.GetResumes,
          request_deserializer=resume__pb2.ResumeRequest.FromString,
          response_serializer=resume__pb2.ResumeResponse.SerializeToString,
      ),
      'SendResumes': grpc.unary_unary_rpc_method_handler(
          servicer.SendResumes,
          request_deserializer=resume__pb2.ResumeResponse.FromString,
          response_serializer=resume__pb2.ResumeRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.ResumeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
