// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/resume.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ported to protobuf
type Resume struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Specs                string   `protobuf:"bytes,4,opt,name=Specs,proto3" json:"Specs,omitempty"`
	Salary               string   `protobuf:"bytes,5,opt,name=Salary,proto3" json:"Salary,omitempty"`
	Zgr                  []string `protobuf:"bytes,6,rep,name=Zgr,proto3" json:"Zgr,omitempty"`
	ExpTitle             string   `protobuf:"bytes,7,opt,name=ExpTitle,proto3" json:"ExpTitle,omitempty"`
	Experience           []string `protobuf:"bytes,8,rep,name=Experience,proto3" json:"Experience,omitempty"`
	Skills               []string `protobuf:"bytes,9,rep,name=Skills,proto3" json:"Skills,omitempty"`
	Driver               string   `protobuf:"bytes,10,opt,name=Driver,proto3" json:"Driver,omitempty"`
	About                string   `protobuf:"bytes,11,opt,name=About,proto3" json:"About,omitempty"`
	Recomend             string   `protobuf:"bytes,12,opt,name=Recomend,proto3" json:"Recomend,omitempty"`
	Portfolio            string   `protobuf:"bytes,13,opt,name=Portfolio,proto3" json:"Portfolio,omitempty"`
	Education            []string `protobuf:"bytes,14,rep,name=Education,proto3" json:"Education,omitempty"`
	Langs                string   `protobuf:"bytes,15,opt,name=Langs,proto3" json:"Langs,omitempty"`
	AdditionalEducation  []string `protobuf:"bytes,16,rep,name=Additional_education,json=AdditionalEducation,proto3" json:"Additional_education,omitempty"`
	Tests                []string `protobuf:"bytes,17,rep,name=Tests,proto3" json:"Tests,omitempty"`
	Certificates         string   `protobuf:"bytes,18,opt,name=Certificates,proto3" json:"Certificates,omitempty"`
	AdditionalInfo       string   `protobuf:"bytes,19,opt,name=Additional_info,json=AdditionalInfo,proto3" json:"Additional_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resume) Reset()         { *m = Resume{} }
func (m *Resume) String() string { return proto.CompactTextString(m) }
func (*Resume) ProtoMessage()    {}
func (*Resume) Descriptor() ([]byte, []int) {
	return fileDescriptor_715f3cd67286bb1f, []int{0}
}

func (m *Resume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resume.Unmarshal(m, b)
}
func (m *Resume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resume.Marshal(b, m, deterministic)
}
func (m *Resume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resume.Merge(m, src)
}
func (m *Resume) XXX_Size() int {
	return xxx_messageInfo_Resume.Size(m)
}
func (m *Resume) XXX_DiscardUnknown() {
	xxx_messageInfo_Resume.DiscardUnknown(m)
}

var xxx_messageInfo_Resume proto.InternalMessageInfo

func (m *Resume) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Resume) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Resume) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Resume) GetSpecs() string {
	if m != nil {
		return m.Specs
	}
	return ""
}

func (m *Resume) GetSalary() string {
	if m != nil {
		return m.Salary
	}
	return ""
}

func (m *Resume) GetZgr() []string {
	if m != nil {
		return m.Zgr
	}
	return nil
}

func (m *Resume) GetExpTitle() string {
	if m != nil {
		return m.ExpTitle
	}
	return ""
}

func (m *Resume) GetExperience() []string {
	if m != nil {
		return m.Experience
	}
	return nil
}

func (m *Resume) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Resume) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Resume) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Resume) GetRecomend() string {
	if m != nil {
		return m.Recomend
	}
	return ""
}

func (m *Resume) GetPortfolio() string {
	if m != nil {
		return m.Portfolio
	}
	return ""
}

func (m *Resume) GetEducation() []string {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *Resume) GetLangs() string {
	if m != nil {
		return m.Langs
	}
	return ""
}

func (m *Resume) GetAdditionalEducation() []string {
	if m != nil {
		return m.AdditionalEducation
	}
	return nil
}

func (m *Resume) GetTests() []string {
	if m != nil {
		return m.Tests
	}
	return nil
}

func (m *Resume) GetCertificates() string {
	if m != nil {
		return m.Certificates
	}
	return ""
}

func (m *Resume) GetAdditionalInfo() string {
	if m != nil {
		return m.AdditionalInfo
	}
	return ""
}

type ResumeRequest struct {
	ID                   []string `protobuf:"bytes,1,rep,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeRequest) Reset()         { *m = ResumeRequest{} }
func (m *ResumeRequest) String() string { return proto.CompactTextString(m) }
func (*ResumeRequest) ProtoMessage()    {}
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_715f3cd67286bb1f, []int{1}
}

func (m *ResumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeRequest.Unmarshal(m, b)
}
func (m *ResumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeRequest.Marshal(b, m, deterministic)
}
func (m *ResumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeRequest.Merge(m, src)
}
func (m *ResumeRequest) XXX_Size() int {
	return xxx_messageInfo_ResumeRequest.Size(m)
}
func (m *ResumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeRequest proto.InternalMessageInfo

func (m *ResumeRequest) GetID() []string {
	if m != nil {
		return m.ID
	}
	return nil
}

type ResumeResponse struct {
	Resumes              []*Resume `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResumeResponse) Reset()         { *m = ResumeResponse{} }
func (m *ResumeResponse) String() string { return proto.CompactTextString(m) }
func (*ResumeResponse) ProtoMessage()    {}
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_715f3cd67286bb1f, []int{2}
}

func (m *ResumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeResponse.Unmarshal(m, b)
}
func (m *ResumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeResponse.Marshal(b, m, deterministic)
}
func (m *ResumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeResponse.Merge(m, src)
}
func (m *ResumeResponse) XXX_Size() int {
	return xxx_messageInfo_ResumeResponse.Size(m)
}
func (m *ResumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeResponse proto.InternalMessageInfo

func (m *ResumeResponse) GetResumes() []*Resume {
	if m != nil {
		return m.Resumes
	}
	return nil
}

func init() {
	proto.RegisterType((*Resume)(nil), "pb.Resume")
	proto.RegisterType((*ResumeRequest)(nil), "pb.ResumeRequest")
	proto.RegisterType((*ResumeResponse)(nil), "pb.ResumeResponse")
}

func init() {
	proto.RegisterFile("pb/resume.proto", fileDescriptor_715f3cd67286bb1f)
}

var fileDescriptor_715f3cd67286bb1f = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4f, 0x1b, 0x31,
	0x10, 0xc5, 0x21, 0x09, 0x0b, 0x99, 0x40, 0x02, 0x03, 0xaa, 0xac, 0xa8, 0x6a, 0xd1, 0xaa, 0x52,
	0x39, 0x05, 0x95, 0xaa, 0xdc, 0x69, 0x13, 0x55, 0x91, 0x38, 0x54, 0x1b, 0x4e, 0x5c, 0xaa, 0xfd,
	0x33, 0x41, 0x56, 0x17, 0xdb, 0xb5, 0x1d, 0x44, 0x2f, 0xfd, 0x0c, 0xfd, 0xc8, 0x95, 0xc7, 0xd9,
	0x64, 0x51, 0x7b, 0xdb, 0xf7, 0x7b, 0x6f, 0xfc, 0x46, 0xab, 0x81, 0x91, 0x29, 0x2e, 0x2d, 0xb9,
	0xd5, 0x23, 0x4d, 0x8c, 0xd5, 0x5e, 0x63, 0xc7, 0x14, 0xe9, 0x9f, 0x1e, 0x24, 0x19, 0x43, 0x1c,
	0x42, 0x67, 0x3e, 0x15, 0xbb, 0xe7, 0xbb, 0x17, 0xfd, 0xac, 0x33, 0x9f, 0xe2, 0x18, 0x0e, 0x6e,
	0x75, 0x99, 0x7b, 0xa9, 0x95, 0xe8, 0x30, 0xdd, 0x68, 0x3c, 0x83, 0xbd, 0x3b, 0xe9, 0x6b, 0x12,
	0x5d, 0x36, 0xa2, 0x08, 0x74, 0x61, 0xa8, 0x74, 0xa2, 0x17, 0x29, 0x0b, 0x7c, 0x05, 0xc9, 0x22,
	0xaf, 0x73, 0xfb, 0x4b, 0xec, 0x31, 0x5e, 0x2b, 0x3c, 0x86, 0xee, 0xfd, 0x83, 0x15, 0xc9, 0x79,
	0xf7, 0xa2, 0x9f, 0x85, 0xcf, 0xd0, 0x38, 0x7b, 0x36, 0xf1, 0xe1, 0xfd, 0xd8, 0xd8, 0x68, 0x7c,
	0x03, 0x30, 0x7b, 0x36, 0x64, 0x25, 0xa9, 0x92, 0xc4, 0x01, 0x0f, 0xb5, 0x08, 0xb7, 0xfc, 0x90,
	0x75, 0xed, 0x44, 0x9f, 0xbd, 0xb5, 0x0a, 0x7c, 0x6a, 0xe5, 0x13, 0x59, 0x01, 0xb1, 0x3d, 0xaa,
	0xb0, 0xeb, 0x4d, 0xa1, 0x57, 0x5e, 0x0c, 0xe2, 0xae, 0x2c, 0xc2, 0x06, 0x19, 0x95, 0xfa, 0x91,
	0x54, 0x25, 0x0e, 0xe3, 0x06, 0x8d, 0xc6, 0xd7, 0xd0, 0xff, 0xa6, 0xad, 0x5f, 0xea, 0x5a, 0x6a,
	0x71, 0xc4, 0xe6, 0x16, 0x04, 0x77, 0x56, 0xad, 0xd6, 0xbf, 0x6b, 0xc8, 0x2b, 0x6c, 0x41, 0x68,
	0xbb, 0xcd, 0xd5, 0x83, 0x13, 0xa3, 0xd8, 0xc6, 0x02, 0x3f, 0xc0, 0xd9, 0x4d, 0x55, 0xc9, 0x90,
	0xc8, 0xeb, 0xef, 0xb4, 0x19, 0x3f, 0xe6, 0xf1, 0xd3, 0xad, 0xf7, 0xe2, 0xa1, 0x3b, 0x72, 0xde,
	0x89, 0x13, 0xce, 0x44, 0x81, 0x29, 0x1c, 0x7e, 0x21, 0xeb, 0xe5, 0x52, 0x96, 0xb9, 0x27, 0x27,
	0x90, 0x5b, 0x5e, 0x30, 0x7c, 0x0f, 0xa3, 0x56, 0x99, 0x54, 0x4b, 0x2d, 0x4e, 0x39, 0x36, 0xdc,
	0xe2, 0xb9, 0x5a, 0xea, 0xf4, 0x2d, 0x1c, 0xc5, 0x8b, 0xc8, 0xe8, 0xe7, 0x8a, 0x9c, 0xdf, 0x1c,
	0x46, 0x37, 0x1e, 0x46, 0x7a, 0x0d, 0xc3, 0x26, 0xe0, 0x8c, 0x56, 0x8e, 0xf0, 0x1d, 0xec, 0xc7,
	0xcb, 0x72, 0x1c, 0x1b, 0x5c, 0xc1, 0xc4, 0x14, 0x93, 0x75, 0xa8, 0xb1, 0xae, 0x7e, 0x37, 0x0f,
	0x2f, 0xc8, 0x3e, 0xc9, 0x92, 0xf0, 0x13, 0xc0, 0x57, 0xf2, 0x91, 0x39, 0x3c, 0x69, 0xcd, 0xc4,
	0xe6, 0x31, 0xb6, 0x51, 0xec, 0x4a, 0x77, 0xf0, 0x1a, 0x06, 0x0b, 0x52, 0x55, 0x33, 0xf7, 0x9f,
	0xd0, 0xf8, 0xdf, 0xb7, 0xd2, 0x9d, 0xcf, 0xc9, 0x7d, 0x6f, 0x72, 0x69, 0x8a, 0x22, 0xe1, 0xf3,
	0xff, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xbd, 0x0f, 0x8a, 0x11, 0x03, 0x00, 0x00,
}
