FROM debian:rc-buggy-20231030
RUN apt-get update && apt-get install python3
RUN apt-get install pipx
RUN pipx install sentence_transformers
RUN apt-get install python3-num2words
RUN apt-get install python3-bertopic
RUN apt-get install python3-re
RUN apt-get install python3-json
RUN apt-get install python3-nltk
RUN apt-get install python3-string
RUN apt-get install python3-tqdm
RUN apt-get install python3-matplotlib
RUN apt-get install python3-np
RUN pipx install spacy
RUN pipx install sentence_transformers 
RUN !python -m spacy download ru_core_news_lg